obstacle_range: 2.5
raytrace_range: 3.0

inflation_radius: 0.35
#footprint: [[0.175, 0.175], [0.175, -0.175], [-0.175, -0.175], [-0.175, 0.175]]
#footprint_inflation: 0.01
# 0.5*0.6
#robot_radius: 0.35
footprint: [ [0.3302, -0.0508], [0.254, -0.0508], [0.254, -0.254], [-0.254, -0.254], [-0.254, 0.254], [0.254, 0.254], [0.254, 0.0508], [0.3302, 0.0508] ]

map_type: costmap

observation_sources: scan
scan: {data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true, expected_update_rate: 0.0}
#observation_sources: scan sonar
#scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
#sonar: {data_type: PointCloud, topic: /RosAria/sonar, marking: true, clearing: true}
